### ISSUE TITLE
Create GitHub action

### ISSUE THREAD

**Issue by stackotter** [stackotter/SwiftGtkUI#8]
A GitHub action would be useful because it allows all supported platforms to be tested for each commit, making it a lot harder to break platform support.

The following two GitHub actions would be the most useful:

- [ ] SwiftLint
- [x] `swift build` on macOS
- [x] `swift build` on Linux

**Comment by NinjaCheetah** [comment]
I'll put some work into this. GitHub Actions is generally one of my strong suits.

I'd say about an hour and I can give it a try.

**Comment by stackotter** [comment]
I'll make a new issue for swift lint, thanks for creating the actions!
